import { useState, useEffect } from "react";

const MESSAGES = [
  // ── Action phrases (legal dramatics) ──────────────────────────────────────
  "Weighing precedents on the scales of justice…",
  "Consulting the corpus juris…",
  "Scanning the legislative landscape…",
  "Deliberating the finer points of law…",
  "Invoking the spirit of the Constitution…",
  "Cross-referencing case law and statutes…",
  "Summoning judicial reasoning…",
  "Navigating the labyrinth of legislation…",
  "Parsing the letter of the law…",
  "Canvassing the jurisprudence…",
  "Examining the annals of precedent…",
  "Marshalling the authorities…",
  "Sifting through the codified wisdom…",
  "Distilling the ratio decidendi…",
  "Tracing the legislative intent…",
  "Calibrating the balance of equities…",
  "Weighing the mens rea against the actus reus…",
  "Consulting the obiter dicta for guidance…",
  "Applying the principle of stare decisis…",
  "Traversing the highways of constitutional jurisprudence…",
  "Interrogating the statutory framework…",
  "Harmonising conflicting provisions…",
  "Probing the legislative intent behind the enactment…",
  "Applying the golden rule of statutory interpretation…",
  "Invoking the mischief rule to seek legislative purpose…",
  "Consulting the principle of purposive construction…",
  "Verifying the locus standi of the submission…",
  "Tracing the constitutional ancestry of the right…",
  "Examining the ambit of judicial review…",
  "Applying the doctrine of proportionality…",
  "Considering the doctrine of legitimate expectation…",
  "Assessing the balance of convenience…",
  "Gathering the prima facie evidence…",
  "Consulting the principle of natural justice…",
  "Applying the rule against bias — nemo iudex in causa sua…",
  "Evaluating the audi alteram partem requirement…",
  "Canvassing the doctrine of res judicata…",
  "Probing the contours of sovereign immunity…",
  "Navigating the doctrine of ultra vires…",
  "Applying the pith and substance doctrine…",
  "Resolving conflicts under the doctrine of repugnancy…",
  "Tracing the evolution of Article 21 jurisprudence…",
  "Examining the fundamental rights framework…",
  "Consulting the Directive Principles of State Policy…",
  "Marshalling the constitutional safeguards…",
  "Weighing the competing constitutional values…",
  "Calibrating the executive, legislative, and judicial boundaries…",
  "Consulting the doctrine of separation of powers…",
  "Applying the principle of harmonious construction…",
  "Tracing the evolution of judicial activism in India…",
  "Examining the boundaries of PIL jurisdiction…",
  "Reviewing the three-part test for reasonable restrictions…",
  "Assessing the constitutional validity of the impugned provision…",
  "Canvassing the doctrine of procedural due process…",
  "Navigating the intersection of statute and precedent…",
  "Weighing the quantum of relief to be granted…",
  "Scrutinising the vires of the delegated legislation…",
  "Consulting the principle of ejusdem generis…",
  "Applying the expressio unius est exclusio alterius rule…",
  "Reviewing the schedule of offences and their cognisability…",
  "Deliberating on the admissibility of electronic evidence…",
  "Calibrating the burden of proof — civil or criminal standard…",
  "Examining the doctrine of promissory estoppel…",
  "Consulting the amicus curiae briefs in analogous matters…",
  "Tracing the lineage of the right through constitutional amendments…",
  "Applying the test of manifest arbitrariness…",
  "Invoking the doctrine of colourable legislation…",
  "Scrutinising the doctrine of waiver and acquiescence…",
  "Reviewing the res sub judice position…",
  "Examining the force majeure and frustration of contract…",
  "Consulting the Indian Limitation Act for temporal fences…",
  "Deliberating the scope of injunctive relief…",
  "Tracing the provenance of fiduciary duty…",
  "Examining the interplay of PMLA and the predicate offence…",
  "Consulting the schedule of bailable and non-bailable offences…",
  "Reviewing the requirements for a valid dying declaration…",
  "Applying the test of reasonable classification under Article 14…",
  "Scrutinising the intelligible differentia of the classification…",
  "Consulting precedents on the right to fair trial…",
  "Weighing the evidentiary value of circumstantial evidence…",
  "Tracing the scope of Section 482 — inherent powers of the High Court…",
  "Deliberating the maintainability of the special leave petition…",
  "Applying the doctrine of merger of judgments…",
  "Reviewing the conditions for anticipatory bail under Section 438…",
  "Consulting the principles governing grant of interim stay…",
  "Examining the threshold for constitutional morality…",
  "Tracing the genesis of the Basic Structure doctrine…",
  "Weighing the test of irreparable harm for injunctions…",
  "Navigating the tribunal's jurisdiction over the lis…",
  "Examining the scope of judicial notice under the Evidence Act…",
  "Deliberating on the doctrine of forum non conveniens…",
  "Consulting authorities on the liability of the state in tort…",
  "Tracing the evolution of strict and absolute liability…",
  "Reviewing the doctrine of command responsibility…",
  "Scrutinising the standard of proof — balance of probabilities…",

  // ── Verified Indian law facts ──────────────────────────────────────────────
  "Did you know? India's Constitution — ~145,000 words — is the world's longest written constitution.",
  "Did you know? Article 32 was called the 'heart and soul' of the Constitution by Dr. B.R. Ambedkar.",
  "Did you know? Kesavananda Bharati v. State of Kerala (1973) was argued before a 13-judge bench over 68 days.",
  "Did you know? India's Evidence Act of 1872 has guided courts for over 150 years.",
  "Did you know? The Supreme Court of India receives over 70,000 fresh cases every year.",
  "Did you know? Article 21 now encompasses privacy, livelihood, health, education, and a dignified life.",
  "Did you know? The POSH Act 2013 traces its origins to the Vishaka Guidelines laid down in 1997.",
  "Did you know? The RTI Act (2005) mandates government response within 30 days of any application.",
  "Did you know? India has 25 High Courts serving 28 states and 8 Union Territories.",
  "Did you know? Maneka Gandhi v. Union of India (1978) expanded Article 21 to require 'due process'.",
  "Did you know? Legal aid in India is a fundamental right under Article 39-A of the Constitution.",
  "Did you know? The Bharatiya Nyaya Sanhita 2023 replaced the IPC, effective July 1, 2024.",
  "Did you know? India's first Law Commission was constituted in 1955 under M.C. Setalvad.",
  "Did you know? Under CPC Order 39, courts can grant ad-interim injunctions within 24 hours.",
  "Did you know? The IPC of 1860 remained the backbone of Indian criminal law for 163 years.",
  "Did you know? Triple Talaq was declared unconstitutional in Shayara Bano v. Union of India (2017).",
  "Did you know? India adopted its Constitution on 26 November 1949, enforced on 26 January 1950.",
  "Did you know? The Supreme Court has suo motu powers to take cognisance of matters of public importance.",
  "Did you know? Article 141 binds all courts in India to follow Supreme Court precedent.",
  "Did you know? The Consumer Protection Act 2019 introduced class-action suits in Indian consumer law.",
  "Did you know? The PMLA 2002 places the burden of proving innocent origin of property on the accused.",
  "Did you know? Judicial appointments are governed by the Collegium system from the Three Judges Cases.",
  "Did you know? India's DPDP Act 2023 is the country's first comprehensive data protection legislation.",
  "Did you know? KS Puttaswamy v. Union of India (2017) unanimously declared privacy a fundamental right.",
  "Did you know? ADM Jabalpur's majority on suspension of Article 21 was overruled 41 years later in 2017.",
  "Did you know? The Arbitration and Conciliation Act 1996 aligned India with the UNCITRAL Model Law.",
  "Did you know? India is a signatory to the New York Convention, making foreign awards enforceable here.",
  "Did you know? The NDPS Act 1985 places a reverse burden of proof on the accused in certain cases.",
  "Did you know? Prevention of Corruption (Amendment) Act 2018 criminalised the bribe-giver for the first time.",
  "Did you know? Under Article 226, High Courts may issue writs against private bodies performing public functions.",
  "Did you know? Section 482 CrPC (now BNSS equivalent) empowers High Courts to quash FIRs to prevent abuse of process.",
  "Did you know? India has specialised tribunals: NCLT, NCLAT, TDSAT, NGT, DRT, SAT, and CAT.",
  "Did you know? The Contempt of Courts Act 1971 distinguishes civil contempt from criminal contempt.",
  "Did you know? The Specific Relief Act 1963 (amended 2018) made specific performance the rule, not the exception.",
  "Did you know? The Companies Act 2013 introduced the concept of class-action suits under Section 245.",
  "Did you know? Order 7 Rule 11 CPC allows courts to reject a plaint that discloses no cause of action.",
  "Did you know? Indian courts follow the 'preponderance of probabilities' standard in civil matters.",
  "Did you know? The Insolvency and Bankruptcy Code 2016 consolidated 12 separate insolvency laws.",
  "Did you know? Under RERA 2016, builders must deposit 70% of project funds in an escrow account.",
  "Did you know? The Competition Act 2002 established the CCI to prevent anti-competitive practices.",
  "Did you know? Article 20(3) of the Constitution guarantees the right against self-incrimination.",
  "Did you know? The POSCO Act 2012 uses a child-friendly court procedure and special public prosecutors.",
  "Did you know? India's first Legal Services Authority Act (1987) ensures free legal aid to the marginalised.",

  // ── Latin maxims with plain-language meanings ──────────────────────────────
  "Legal maxim: Actus non facit reum nisi mens sit rea — An act alone does not create guilt without a guilty mind.",
  "Legal maxim: Audi alteram partem — Hear the other side. The cornerstone of natural justice.",
  "Legal maxim: Nemo iudex in causa sua — No one shall be a judge in their own cause.",
  "Legal maxim: Ex turpi causa non oritur actio — No action arises from a dishonourable cause.",
  "Legal maxim: In dubio pro reo — When in doubt, decide in favour of the accused.",
  "Legal maxim: Ignorantia juris non excusat — Ignorance of the law excuses no one.",
  "Legal maxim: Lex posterior derogat priori — A later law prevails over an earlier one.",
  "Legal maxim: Fraus omnia corrumpit — Fraud vitiates everything.",
  "Legal maxim: Res ipsa loquitur — The thing speaks for itself. A presumption of negligence.",
  "Legal maxim: Volenti non fit injuria — No injury is done to one who consents.",
  "Legal maxim: Ubi jus, ibi remedium — Where there is a right, there is a remedy.",
  "Legal maxim: Salus populi suprema lex — The welfare of the people is the supreme law.",
  "Legal maxim: Suppressio veri suggestio falsi — Suppression of truth is equivalent to suggestion of falsehood.",
  "Legal maxim: Delegatus non potest delegare — A delegate may not further delegate their authority.",
  "Legal maxim: Dura lex sed lex — The law is harsh, but it is the law.",
  "Legal maxim: Lex specialis derogat legi generali — A specific law prevails over a general law.",
  "Legal maxim: Qui tacet consentire videtur — Silence implies consent, in appropriate circumstances.",
  "Legal maxim: Nemo dat quod non habet — One cannot give what one does not have.",
  "Legal maxim: Caveat emptor — Let the buyer beware.",
  "Legal maxim: Ex nudo pacto actio non oritur — A bare agreement without consideration gives no cause of action.",
  "Legal maxim: In pari delicto potior est conditio possidentis — Where both parties are equally at fault, the possessor prevails.",
  "Legal maxim: Necessitas non habet legem — Necessity knows no law.",
  "Legal maxim: Nullum crimen sine lege — No crime without a law; no punishment without a crime.",
  "Legal maxim: Falsus in uno, falsus in omnibus — False in one thing, false in all things.",
  "Legal maxim: Ut res magis valeat quam pereat — Construe a law so it works rather than fails.",
];

interface AiThinkingTextProps {
  size?: "sm" | "xs";
  color?: string;
}

export function AiThinkingText({ size = "sm", color }: AiThinkingTextProps) {
  const [index, setIndex] = useState(() => Math.floor(Math.random() * MESSAGES.length));
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    const cycle = setInterval(() => {
      setVisible(false);
      setTimeout(() => {
        setIndex((i) => (i + 1) % MESSAGES.length);
        setVisible(true);
      }, 400);
    }, 3500);
    return () => clearInterval(cycle);
  }, []);

  const textClass = size === "xs" ? "text-xs" : "text-sm";
  const style: React.CSSProperties = {
    transition: "opacity 0.4s ease",
    opacity: visible ? 1 : 0,
    fontStyle: "italic",
    color: color ?? undefined,
  };

  return (
    <span className={`${textClass} text-muted-foreground`} style={style}>
      {MESSAGES[index]}
    </span>
  );
}
